import { type NextPage } from 'next';
import type { ClubSeasonGames, Game } from '~/@types';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import DarkModeSwitch from '../components/layout/DarkModeSwitch';
import GameShowcase from '~/components/GameShowcase';

const Home: NextPage = () => {
  const [games, setGames] = useState<Game[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);
    fetch('api/vsports/games/2023/club/fcporto')
      .then((res) => res.json())
      .then((data: ClubSeasonGames) => {
        if (data.games.length > 0) {
          setGames(data.games);
          setLoading(false);
        }
      })
      .catch((err) => console.log(err));
  }, []);

  return (
    <>
      <Head>
        <title>Goals | Porto Lens</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className="flex min-h-screen w-full flex-col bg-gradient-to-b from-blue-800 via-blue-700 to-blue-500 
      dark:from-slate-800 dark:via-slate-800 dark:to-slate-700"
      >
        <section className="flex flex-1 flex-col">
          <div className="flex flex-col bg-white/10 dark:bg-white/5">
            <div className="flex items-center justify-end gap-3 py-4 px-4">
              <DarkModeSwitch large />
            </div>

            {loading ? (
              <div className="bg-rose-700/70 px-4 py-4 text-center text-white">Loading...</div>
            ) : (
              <div>
                {games.length === 0 ? (
                  <div>No games found</div>
                ) : (
                  <div className="grid grid-cols-1 gap-4 px-4 py-4">
                    {games.map((game: Game, gameIdx: number) => (
                      <GameShowcase key={`game-showcase-${gameIdx}`} game={game} />
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
